apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wallet.fullname" . }}
  labels:
   {{- include "wallet.labels" . | nindent 4 }}
data:
  metrics_exporter: "otlp"
  otel_resource_attributes: "service.name=wallet"
  otel_otlp_endpoint: "http://grafana-k8s-monitoring-grafana-agent.default.svc.cluster.local:4318"
  profile: "{{ .Values.profile }}"
