spring:
  application:
    name: wallet
  threads:
    virtual:
      enabled: true

consumers:
  payment-processing-topic: payment-processing
  financial-reporting-topic: financial-reporting
  merchant-account-topic: merchant-account
